const RidesArray = [
  {
    id: 0,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides2.jpeg",
    text: "Fun Express",
    desc: "A thrilling ride full of twists and turns, suitable for all ages.",
    rideNotFor: "People with heart conditions.",
  },
  {
    id: 1,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides3.jpeg",
    text: "Cycle Monorail",
    desc: "An exciting monorail experience on a cycle-themed ride.",
    rideNotFor: "Pregnant women.",
  },
  {
    id: 2,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides4.jpeg",
    text: "Techno Jump",
    desc: "Get ready for a techno-infused jumping adventure in this ride.",
    rideNotFor: "Individuals with back problems.",
  },
  {
    id: 3,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides5.jpeg",
    text: "Shark Ride",
    desc: "Embark on a thrilling journey through the jaws of a virtual shark.",
    rideNotFor: "People with a fear of heights.",
  },
  {
    id: 4,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides6.jpeg",
    text: "Mini Train",
    desc: "A delightful mini train ride suitable for families and children.",
    rideNotFor: "People with motion sickness.",
  },
  {
    id: 5,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides7.jpeg",
    text: "Flying Appu",
    desc: "Soar through the air on the back of a flying elephant in this whimsical ride.",
    rideNotFor: "People with neck problems.",
  },
  {
    id: 6,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides8.jpeg",
    text: "Kiddy Swing Chair",
    desc: "A gentle swinging experience designed for young children.",
    rideNotFor: "Adults exceeding weight limit.",
  },
  {
    id: 7,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides9.jpeg",
    text: "Carousel",
    desc: "Classic carousel ride with beautifully adorned horses and music.",
    rideNotFor: "People with dizziness issues.",
  },
  {
    id: 8,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides10.jpeg",
    text: "Matter Horn",
    desc: "Experience the twists and turns of a mountain-themed ride.",
    rideNotFor: "People with claustrophobia.",
  },
  {
    id: 9,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides12.webp",
    text: "Power Surge",
    desc: "Feel the adrenaline rush on this high-powered surge ride.",
    rideNotFor: "Individuals with heart conditions.",
  },
  {
    id: 10,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides13.webp",
    text: "Tsunami",
    desc: "Ride the waves on this exhilarating tsunami-themed attraction.",
    rideNotFor: "Pregnant women and individuals with motion sickness.",
  },
  {
    id: 11,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides14.webp",
    text: "Roller Coaster",
    desc: "Experience the ultimate thrill with twists and loops on this roller coaster.",
    rideNotFor: "People with a fear of heights.",
  },
  {
    id: 12,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides15.webp",
    text: "Pendulum",
    desc: "Swing back and forth on this pendulum ride for an exhilarating experience.",
    rideNotFor: "Individuals with back problems.",
  },
  {
    id: 13,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides16.webp",
    text: "High Tower",
    desc: "Rise to new heights on this tower ride with breathtaking views.",
    rideNotFor: "People with a fear of heights.",
  },
  {
    id: 14,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides17.webp",
    text: "Sky Drop",
    desc: "Freefall from the sky in this heart-pounding drop attraction.",
    rideNotFor: "People with heart conditions.",
  },
  {
    id: 15,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides18.webp",
    text: "Wind Mill",
    desc: "Spin around in the wind on this whimsical windmill-themed ride.",
    rideNotFor: "Individuals prone to motion sickness.",
  },
  {
    id: 16,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides19.webp",
    text: "Kiddy Tagada",
    desc: "A fun and bumpy ride designed for young adventurers.",
    rideNotFor: "Adults exceeding weight limit.",
  },
  {
    id: 17,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides20.webp",
    text: "Motor Bike",
    desc: "Race through the air on this thrilling motorbike-inspired ride.",
    rideNotFor: "People with back problems.",
  },
  {
    id: 18,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides21.webp",
    text: "Helicopter",
    desc: "Take to the skies in a helicopter-themed ride for a unique adventure.",
    rideNotFor: "People with a fear of heights.",
  },
  {
    id: 19,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides22.webp",
    text: "Revolving Tower",
    desc: "Rotate and enjoy panoramic views from this towering attraction.",
    rideNotFor: "People with dizziness issues.",
  },
  {
    id: 20,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides23.webp",
    text: "Mini Pirate Ship",
    desc: "Set sail on a mini pirate ship for a swashbuckling adventure.",
    rideNotFor: "People with motion sickness.",
  },
  {
    id: 21,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides24.webp",
    text: "Children Jeep",
    desc: "An off-road jeep adventure designed specifically for children.",
    rideNotFor: "Adults exceeding weight limit.",
  },
  {
    id: 22,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides25.webp",
    text: "NFS Car",
    desc: "Race in style on this NFS-inspired car ride with sharp turns and speed.",
    rideNotFor: "People with a history of heart conditions.",
  },
  {
    id: 23,
    img: "https://funworldblr.s3.amazonaws.com/public/Amusement/rides26.webp",
    text: "Flying Tiger",
    desc: "Experience the thrill of flying high on a tiger-themed ride.",
    rideNotFor: "Children below 3 years old.",
  },
];

export default RidesArray;
